name: construction_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+11
  flushbar: ^1.10.4
  provider: ^4.3.2+2
  positioned_tap_detector: ^1.0.3
  photo_view: ^0.10.2
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^4.0.1
  cached_network_image: ^2.3.2+1
  progress_dialog: ^1.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true